image: docker:latest
services:
  - docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/n0ir1/bandit-alerts-api .
    - docker push registry.gitlab.com/n0ir1/bandit-alerts-api
  only:
    - master
